name: Python Checks

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  schedule:
      - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup
      run: |
        python -Im pip install --upgrade pip
        python -Im pip install nox
    - name: Report Dependencies
      run: |
        python -Im pip freeze
        python -Im nox -R -s cli -- pip freeze
    - name: Run Nox Checks
      run: |
        python -Im nox -R -s lint
        python -Im nox -R -s test
